name: nlp-letters
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.2.4
  - scikit-learn
  - evaluate
  - numpy
  - pandas
  - matplotlib
  - pytorch::pytorch
  - pip:
      - transformers
      - datasets
      - accelerate